import dynamic from 'next/dynamic';
import Head from 'next/head';

const Logo = dynamic(() => import('@/components/canvas/Logo'), { ssr: false });

const HomePage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main css={{ fontSize: 24 }}>home</main>
    </>
  );
};

HomePage.canvas = () => <Logo scale={0.5} route='/blob' position-y={-1} />;

export default HomePage;
